version: '3.9'

services:
  sql-server:
    container_name: mssql
    image: mcr.microsoft.com/mssql/server:latest
    user: root
    ports:
      - '1433:1433'
    environment:
      SA_PASSWORD: 'Sazzad14#' # Set your desired SA password here
      ACCEPT_EULA: 'Y'
      MSSQL_PID: 'Developer'
      MSSQL_USER: 'sa' # created username is sa
      MSSQL_PASSWORD: 'Sazzad14#'
    volumes:
      - mssql:/var/opt/mssql/data # Mount volume to persist data

volumes:
  mssql:
