# version: "3.8"
# services:
#   zookeeper:
#     image: confluentinc/cp-zookeeper:latest
#     environment:
#       ZOOKEEPER_CLIENT_PORT: 2181
#       ZOOKEEPER_TICK_TIME: 2000
#     ports:
#       - "2181:2181"

#   kafka:
#     image: confluentinc/cp-kafka:latest
#     ports:
#       - "9092:9092"
#     environment:
#       KAFKA_BROKER_ID: 1
#       KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#       KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
#       KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
#     depends_on:
#       - zookeeper

services:
  kafka:
    container_name: kafka
    image: moeenz/docker-kafka-kraft:latest
    platform: linux/amd64
    restart: always
    ports:
      - "9093:9093"
    environment:
      - KRAFT_CONTAINER_HOST_NAME=kafka
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9093
      # - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9093 #for localhost
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://192.168.0.159:9093
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
