services:
  redis:
    build: .
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - redis_network
    environment:
      - redis_password=sazzad14

    command:
      [
        "redis-server",
        "/usr/local/etc/redis/redis.conf",
        "--appendonly",
        "yes",
        "--appendfsync",
        "everysec",
        "--requirepass",
        "sazzad14",
      ]

volumes:
  redis_data:
    driver: local

networks:
  redis_network:
    driver: bridge
